### ISSUE TITLE
--force flag not working in v4.0.0

### ISSUE THREAD

**Issue by michael-dickinson-sainsburys** [about-code/glossarify-md#103]
When reading and writing back to the same folder, the `--force` flag is required. Passing this at the end of the command does not seem to work in v4.0.0 (it worked in v3.6.5), instead, an error is output stating that the flag is required and then the tool aborts.

glossarify-md.conf.json:
```json
{
  "$schema": "./node_modules/glossarify-md/conf.schema.json",
  "baseDir": "./",
  "outDir": "./",
  "glossaries": [
     { "file": "./GLOSSARY.md" }
  ],
  "ignoreCase": true,
  "includeFiles": ["./docs/*/*.md"],
  "excludeFiles": ["node_modules"],
  "linking": "absolute"
}
```

Output:
```
+ npx glossarify-md --config ./glossarify-md.conf.json --baseUrl https://github.com/my-org/my-repo/blob/branch_name --force
npx: installed 129 in 5.808s
┌──────────────────────────┐
│   glossarify-md v4.0.0   │
└──────────────────────────┘

☛ Reading from: /github/workspace
☛ Writing to:   /github/workspace

⚠ Warning: --baseDir and --outDir resolve to the same directory.
Such a config is going to overwrite input files in --baseDir.
Choose a different --outDir or change config provided via --config.
Use --force if you want to proceed with current settings.
See --help for details.

ABORTED.
```

**Comment by about-code** [comment]
Thank you very much for reporting. Would you mind verifing with `npm install glossarify-md@next` that the fix  works for you? 

**Please note that the CLI has changed in version 4.0.0 and `--baseUrl` won't work anymore.** There are now only two options  `--shallow` or `--deep`  to merge a JSON serialized configuration into the one provided by your `glossarify-md.conf.json` file so in your case I recommend

~~~
npx glossarify-md --config ./glossarify-md.conf.json --shallow "{'baseUrl': 'https://github.com/my-org/my-repo/blob/branch_name'}" --force
~~~

This is less convenient to type but makes it easier to provide any options available via the CLI.
