### ISSUE TITLE
Identifier-based cross-linking doesn't provide glossary term preview for bottom page links

### ISSUE THREAD

**Issue by caligo-erik** [about-code/glossarify-md#242]
**Describe the bug**
When using https://github.com/about-code/glossarify-md#identifier-based-cross-linking , the glossary term preview at the end of the glossarified pages doesn't show the preview of the term (while regular glossary terms have a preview)

**To Reproduce**
1. Run the steps described in this guide to create a new glossarify project.
2. Modify the glossary.md file with the following content
```
# Glossary

## Test term

A generic test term to test our glossary.

## Specific link test term {#test-id}

A specific link test term to test exact links to glossary definitions.
```
3. Create a pages/page1.md with the following content
```
# Test page
This is a simple test page

## Introduction
Let's see what happens if I mention a Test term.

## Specific links
Let's see what happens if I use a [specific link](#test-id).
```
4. npm run glossarify
5. Check the glossarified page

**Expected behavior**
The two glossary terms at the end of the page should both have a preview:
```
[1]: ../glossary.md#test-term "A generic test term to test our glossary."

[2]: ../glossary.md#test-id "A specific link test term to test exact links to glossary definitions."
```

**Screenshots**
These are the generated bottom page links:
```
[1]: ../glossary.md#test-term "A generic test term to test our glossary."

[2]: ../glossary.md#test-id
```
The first entry comes with preview: ![glossarify-with-preview](https://user-images.githubusercontent.com/41074607/174472947-873a4975-d8ef-4f52-a3b1-1d3e31bac929.png)
The second entry is without preview: 
![glossarify-no-preview](https://user-images.githubusercontent.com/41074607/174472945-ed2936b7-9779-4b28-be7e-b1e49aadae0b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - glossarify-md version v6.2.0 

**Additional context**
No additional context

**Comment by about-code** [comment]
Thank you very much for the concise issue report and sorry for being so late to respond. 
You'll find the bug fixed in the upcoming version 6.2.1.
