### ISSUE TITLE
One empty heading breaks glossarify-md, doesn't render any terms, terminates

### ISSUE THREAD

**Issue by christophcemper** [about-code/glossarify-md#257]
**Describe the bug**
When you have a file with an empty H4 heading (####) 
somewhere in your source files, glossarify now 
runs forever, generates no links and then crashes with a terrible cryptic error message

It appears to have surfaced in the past weeks.

```
☛ Reading from: /home/christophc/learn_glossarify/docs
☛ Writing to:   /home/christophc/learn_glossarify/docs-glossarified

glossary.md: no issues found
pages/page1.md: no issues found
pages/page2.md: no issues found
TypeError: Cannot read properties of undefined (reading 'localeCompare')
    at file:///home/christophc/node_modules/glossarify-md/lib/exporter.js:60:42
    at Array.sort (<anonymous>)
    at exportGlossaries (file:///home/christophc/node_modules/glossarify-md/lib/exporter.js:60:10)
    at Module.run (file:///home/christophc/node_modules/glossarify-md/lib/main.js:26:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/christophc/node_modules/glossarify-md/bin/index.js:210:13
```

**To Reproduce**
[glossarify-631-empty-header-defect.zip](https://github.com/about-code/glossarify-md/files/9882924/glossarify-631-empty-header-defect.zip)

I created a mini project, after spending hours isolating where the problem in our overall source code base was.

1. unzip the file
2. run npm glossarify
3. get the same terrible error message

**Expected behavior**
A clear and concise error message about which file, term, etc. was processed that caused the "undefined" crash.

**Screenshots**

![image](https://user-images.githubusercontent.com/12080594/198391025-fb03706b-b414-4954-8295-bb9e5676831a.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.10
 - glossarify-md version: 6.3.1

**Comment by about-code** [comment]
Thank you for your very much for your detailed bug report and attached files.

**Comment by about-code** [comment]
Eventually, I chose to fix the root cause by not treating empty headings like terms anymore. I hope this makes you even more happy than getting a better error message ;-). 

If your intent or expection was to just get a hint where to find an empty heading, then you may try using glossarify-md with [remark-lint](https://npmjs.com/package/remark-lint) and [remark-lint-heading-word-length](https://www.npmjs.com/package/remark-lint-heading-word-length).
