### ISSUE TITLE
Glossary-terms flanked by ( or ) wouldn't get linked

### ISSUE THREAD

**Issue by MrGung** [about-code/glossarify-md#37]
Hi,

I am using glossrify-md v2.0.0 together with vuepress 1.0.0.

I've a term "SC" which will get linked to in
`(OnPremises SC↵ or other stuff)`

but it wouldn't in 
`(OnPremises SC)`

**Comment by about-code** [comment]
Thanks for reporting. I'll try reproducing it with a test.

**Comment by MrGung** [comment]
Works! Thanks!
