### ISSUE TITLE
Aliases not working

### ISSUE THREAD

**Issue by Fischermaen** [about-code/glossarify-md#41]
I have this code in the `glossary.md` of my project.

```md
## Issue
<!-- Aliases: Issues -->
Damit wird der Verstoß gegen eine SonarQube-Regel bezeichnet.
```

While the word "Issue" is found and linked to the glossatry without any problem, "Issues" is not found at all in any constellation.

**Comment by about-code** [comment]
Well, hmm... I whish I could congratulate for finding an easter egg but this issue with Issues is quite an issue. I'll try to reproduce it with a test case. 

Meanwhile: what version of *glossarify-md* do you use?

**Comment by about-code** [comment]
Okay, I can reliably reproduce it with the current version of *glossarify-md*. While I have tested substring behavior without aliases, the particular issue here is that the term *Issue* is a substring of the alias *Issues*. Very nice catch!
