### ISSUE TITLE
option to add inline title attribute to markdown link

### ISSUE THREAD

**Issue by neumayr** [about-code/glossarify-md#9]
Hi @about-code 👋 

Really nice idea to put this into a common Markdown pipeline. 

Markdown would allow adding a title attribute to links [1], what do you think
adding such [optional] functionality based on a flag/option? 

##### expected behaviour `./out/files/file1.md`

```md
# Demo for a Glossary Term

This is a text which uses a [Glossary Term ↴](../glossary.md#glossary-term "A glossary term has a short description. The full description contains both sentences.") to describe something.
```

📝 [1] https://daringfireball.net/projects/markdown/syntax#link

**Comment by about-code** [comment]
I'll put this on the roadmap. Should not take too long to implement. For a first quick-win I will probably add just the short description of a term as a title (the first sentence of its description). But I am also open to allow for the whole first paragraph.
